version: '3.8'

services:

  app:
    container_name: rag_max-prod
    image: rag_max:production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      -  QDRANT_HOST=${QDRANT_HOST}
      -  QDRANT_PORT=${QDRANT_PORT}
      -  API_HOST=${API_HOST}
      -  API_PORT=${API_PORT}
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - rag-max


networks:
  rag-max: